repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-isort==4.1.1"]
        language: python
        language_version: python3
        exclude: |
          (?x)^(
              migrations/ |
          )

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language: python
        language_version: python3
        exclude: |
          (?x)^(
              migrations/ |
          )
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        additional_dependencies:
          ["pylint-django==2.5.1", "pylint-plugin-utils==0.7"]
        language: python
        language_version: python3
        exclude: |
          (?x)^(
              migrations/ |
          )
