version: "3"
services:
  api:
    build: 
      dockerfile: Dockerfile_test
      context: .
    volumes:
      - .:/code
    ports:
      - 80:8000
    env_file:
      - .env_dev
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    build:
      dockerfile: Dockerfile_db
      context: .
    ports:
      - 8001:5432
    env_file:
      - .env_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: