# Generated by Django 4.1.4 on 2022-12-25 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_user_full_name_transactionhistory_orderhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courieradditionaldata',
            name='current_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_courier_data', to='delivery.order'),
        ),
        migrations.AlterField(
            model_name='courieradditionaldata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_courier_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
