# Generated by Django 4.1.4 on 2022-12-29 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_courieradditionaldata_current_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_processed_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
